"""
Django settings for genealogy project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

from django.utils.translation import ugettext as _

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lr#!m*()p++y)m)8e@#t(*so7_ht=*1_c(^7ofsx9hm+*c3m3v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'family',
	'captcha',
)

MIDDLEWARE_CLASSES = (
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'genealogy.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'genealogy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	}
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
	('es', _('Spanish')),
	('en', _('English')),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = '/'

EMAIL_BACKEND ='django.core.mail.backends.console.EmailBackend'

#reCaptcha
RECAPTCHA_PUBLIC_KEY = '6Lezo84SAAAAAK9O-cgYF9sh-Gc4adwj_Mj2o86e'
RECAPTCHA_PRIVATE_KEY = '6Lezo84SAAAAAJrxmlCqpKlgypEjt7aMNQuJtiZE'
NOCAPTCHA = True
RECAPTCHA_USE_SSL = True

#Password Hashing

#PASSWORD_HASHERS = (
#	'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
#	'django.contrib.auth.hashers.BCryptPasswordHasher',
#	'django.contrib.auth.hashers.PBKDF2PasswordHasher',
#	'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
#	'django.contrib.auth.hashers.SHA1PasswordHasher',
#	'django.contrib.auth.hashers.MD5PasswordHasher',
#	'django.contrib.auth.hashers.CryptPasswordHasher',
#)

#BCRYPT_ENABLED = True
