# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0026_auto_20151201_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='member_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='member_partner_id',
        ),
    ]
